### ISSUE TITLE
Constraint Not Iterable

### ISSUE THREAD

**Issue by cjk12** [appliedopt/gpkit#114]
I'm not sure why this isn't working:

`import gpkit as gpkit`
`A = gpkit.mon("A", "-", "Test Variable")`
`gp = gpkit.GP(A, A>=1.3)`   <-------------------------------------
`res_all = gp.solve(printing=False)`
`res = res_all['variables']`
`print type(res['A'])`

I'm getting an error telling me the constraint is not iterable at the indicated line.  Also, I think this is actually returning 'str' and not 'float' as expected.

**Comment by whoburg** [comment]
`GP` expects a list of constraints, so this will work as intended if the indicated line is changed to:

```
gp = gpkit.GP(A, [A>=1.3])
```

**Comment by cjk12** [comment]
Ah, thanks for the heads up.

Cody

**Comment by bqpd** [comment]
This could be changed, if it was worthwhile?

**Comment by cjk12** [comment]
I think it's acceptable as is.

**Comment by whoburg** [comment]
Agreed, I like keeping the API as simple as possible, even if it's a little less friendly.
